Add existingPasswordSecretKey parameter
neo4j-contrib/neo4j-helm pull request #136
Opened 2020-11-16 17:23 UTC by maxbischoff

Enables users of this chart to define the key,
to which the neo4j password is set in 
existingPasswordSecret

2020-11-16 21:20 UTC, moxious requested changes
Thanks for the PR!

A few additional things are needed before this can be merged, but I think I get what you're after - rather than using a flat secret, you want to be able to use a particular key within the secret, is that right?

Please have a look at other places in the repo where existingPasswordSecret is mentioned, and make sure that your modification makes sense in those places too.  For example:

* You've modified the core stateful set, but we need the same change carried over to the read replica stateful set
* Check NOTES (here: https://github.com/neo4j-contrib/neo4j-helm/blob/master/templates/NOTES.txt#L30) for the text that gets outputted when helm install is run and make sure it's appropriate for your use case
* Note in the documentation (probably around here: https://github.com/neo4j-contrib/neo4j-helm/blob/master/doc/docs/modules/ROOT/pages/networking.adoc#password) how this change works so others can use it

2020-11-17 06:50 UTC, maxbischoff commented
Thanks for the fast and excellent feedback! I incorporated the changes you mentioned.

2020-11-17 07:37 UTC, maxbischoff commented
> A few additional things are needed before this can be merged, but I think I get what you're after - rather than using a flat secret, you want to be able to use a particular key within the secret, is that right?

That's correct, when defining my own secret I would like to have the flexibility to also define the key for the password.

2020-11-18 12:10 UTC, moxious approved these changes

2020-11-18 12:10 UTC, merged