Removed minimum cluster size at formation setting
neo4j-contrib/neo4j-helm pull request #203
Opened 2021-06-17 21:34 UTC by bfeshti

2021-06-18 08:43 UTC, alemairebe commented
we now have twice `NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime` on the configmap

2021-06-18 09:54 UTC, eastlondoner requested changes

2021-06-18 09:54 UTC, eastlondoner commented on templates/common-configmap.yaml
> +  NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime: "2"
Sorry bit of confusion here. We should remove `causal__clustering_minimum__core__cluster__size__at__runtime:` as well.

Setting it to 2 by default is not desirable:
see https://neo4j.com/developer/kb/a-demonstration-of-cluster-size-at-formation-and-runtime/ 

Setting it to 3 is just re-stating the default value that Neo4j has and hard coding it to 3 here causes confusion if users of the helm chart want to change it.

2021-07-09 07:29 UTC, eastlondoner approved these changes
LGTM

2021-07-09 07:29 UTC, merged